# Generated by Django 5.1.3 on 2024-11-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_item_battle_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experiencia_necesaria',
            field=models.IntegerField(default=100),
        ),
    ]
